In [5]:
import pandas as pd
import numpy as np
from PIL import Image, ImageEnhance
import pytesseract
import os, os.path
import cv2

In [6]:
train_1=['F:\Misc\Meter Pics\mfaphotos\\'+ name for name in os.listdir('F:\Misc\Meter Pics\mfaphotos') if os.path.isfile(os.path.join('F:\Misc\Meter Pics\mfaphotos', name))]
train_2=['F:\Misc\Meter Pics\mfa photos2\\' + name for name in os.listdir('F:\Misc\Meter Pics\mfa photos2') if os.path.isfile(os.path.join('F:\Misc\Meter Pics\mfa photos2', name))]
train=train_1 +train_2

results={}

# Trial 1

In [8]:
#first running for the dataset as a whole
for i in range(0,len(train)-1):
    if train[i].split('.')[1]!='jpg':
        continue
    img = cv2.resize(np.asarray(Image.open(train[i])) ,(300,300))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    # Apply dilation and erosion to remove some noise
    kernel = np.ones((1, 1), np.uint8)
  
    img = cv2.dilate(img, kernel, iterations=1)
    img = cv2.erode(img, kernel, iterations=1)
    # Apply blur to smooth out the edges
    img = cv2.GaussianBlur(img, (5, 5), 0)
    # Apply threshold to get image with only b&w (binarization)
    img = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]
    print(img)
    # Save the filtered image in the output directory
    type(Image.fromarray(img))
    save_path = os.path.join("F:\Misc\Final_modified", train[i].split() + "_filter_" + ".jpg")
    cv2.imwrite(save_path, img)

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [255 255   0 ...   0   0   0]
 [255 255   0 ...   0   0   0]
 [255 255 255 ...   0   0   0]]


TypeError: can only concatenate list (not "str") to list

In [9]:
img

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [255, 255,   0, ...,   0,   0,   0],
       [255, 255,   0, ...,   0,   0,   0],
       [255, 255, 255, ...,   0,   0,   0]], dtype=uint8)

In [10]:
pytesseract.pytesseract.tesseract_cmd = r'C:\Anaconda3\Scripts\pytesseract.exe'

# TRIAL 2

In [ ]:
#running by taking individual examples
i=2
img = cv2.resize(np.asarray(Image.open(train[i])) ,(300,300))
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

print(Image.fromarray(img))
# Apply dilation and erosion to remove some noise
kernel = np.ones((1, 1), np.uint8)
  
img = cv2.dilate(img, kernel, iterations=1)
cv2.imshow('dilate',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
img = cv2.erode(img, kernel, iterations=1)
cv2.imshow('erode',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(Image.fromarray(img))
# Apply blur to smooth out the edges
img = cv2.GaussianBlur(img, (5, 5), 0)
cv2.imshow('GaussianBlur',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
# Apply threshold to get image with only b&w (binarization)
img = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]
cv2.imshow('threshold',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
 result = pytesseract.image_to_string(Image.open(save_path), lang="eng")

In [ ]:
  result = pytesseract.image_to_string(Image.open('F:\\Img_proc\\329_20150520162724_1622208_1984831.jpg_filter_.jpg'))
    print(result)